config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, uniqueness: true, presence: true
    has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
     has_many :doses
    has_many :cocktails, through: :doses
    validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index
        @cocktails = Cocktail.all
      end
    
      def show
        @cocktail = Cocktail.find(params[:id])
        @dose = Dose.new
      end
    
      def new
        @cocktail = Cocktail.new
      end
    
      def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
          redirect_to cocktail_path(@cocktail)
        else
          render 'new'
        end
      end
    
      private
    
      def cocktail_params
        params.require(:cocktail).permit(:name, :photo)
      end
    end

app/controllers/doses_controller.rb
class DosesController < ApplicationController  
    def create
        @cocktail = Cocktail.find(params[:cocktail_id])
        @dose = Dose.new(dose_params)
        @dose.cocktail = @cocktail
        if @dose.save
          redirect_to cocktail_path(@cocktail)
        else
          @review = Review.new
          render "cocktails/show"
        end
      end
    
      def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy
        redirect_to cocktail_path(@dose.cocktail)
      end
    
      private
    
      def dose_params
        params.require(:dose).permit(:description, :ingredient_id)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
  
<div class="navbar navbar-expand navbar-light navbar-lewagon one fixed-top">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <i class="fas fa-cocktail"></i>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Add cocktail", new_cocktail_path, class: "nav-link", style: "color: purple" %>
          </li>
          </ul>
          </div>
    </div>
<br>
<br>
<br>
 
<div class="pl-3">
<% @cocktails.each do |cocktail| %>
<h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
<% end %> 
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/cocktails/new.html.erb
  
<div class="navbar navbar-expand navbar-light navbar-lewagon one fixed-top">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <i class="fas fa-cocktail"></i>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Add cocktail", new_cocktail_path, class: "nav-link", style: "color: purple" %>
          </li>
          </ul>
          </div>
    </div>
<br>
<br>
<br>
<h1>My cocktails</h1>
<%= simple_form_for @cocktail do|f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit "create new cocktail" %>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/cocktails/show.html.erb
  <div class="navbar navbar-expand navbar-light navbar-lewagon one fixed-top">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
        <i class="fas fa-cocktail"></i>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Add cocktail", new_cocktail_path, class: "nav-link", style: "color: purple" %>
          </li>
          </ul>
          </div>
  
    </div>
  <br>
  <br>
  <br>
  <br> 
  <br>
  <br>
<h1 class="pl-3"><%= @cocktail.name %></h1>
<% @cocktail.doses.each do |dose| %>
<li class="pl-5">
  <%= dose.ingredient.name  %>
  <%= dose.description %>
  </li>
  <% end %>
  <br>
  <br>
  <br>

  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 1500, crop: :fill %>
<br>
<br>
<br>
<br>
<br>
<div class="pl-3">
<%= render "doses/form" %>
</div>
<br>
<br>
<br>
<br>
<br>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| -%>
<%= f.input :description %>
<%= f.association :ingredient %>
<%= f.submit class: 'btn btn-primary' %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %> 
  </body>
</html>